language: node_js
node_js:
  - "8"
cache:
  npm: true
  yarn: true
  directories:
    - "$HOME/terraform"
env:
  global:
    - secure: 2T+why6MSVDYZfYagUX1R61xqw1c23b7plCZDRHSqPeVFWXaK27HVwP7+EZZgo54mRmbrp2hyHjvro2l4oG/d2aEu28adGZ5YY/Wbg+LOc2xI6U5cK/9yPtTLiiGXXCbDCehIqoQKcdhWtfWGo0niN9UcDK1NYjSx8BsG402BjYgTgesjda6VvwFeaHNmwfgiGi+XYRWTEBwPFdW0+du1QMrFUHZxKFPAkW6JGz3Xl0JNWcLCidd9tyhMOw+HZxVpVClYvtYhbasl++oQvQ77mmWrdmxxpmjiF4RazpqT4skxZAsgp7DFK7q71r0wnJeQOXbH8uSwLAoqGHHlt9MZi5GftW0OqdUDGLloIuKXLoMI3mNwnXoUCwFXx6dCjlcXJx63taV+u65yAaOMJ1surzoPLPO0RPpKOROyvBCasrx5ybfXxG3GxZf0uEGBVqP3lhIaxGLMTKNDb3eXmqSCwaGREAsJp+CdFtcOEdLRtUpF2hrVTY/fkLTo7FBO7ecU6xHGqqLS9Y7xlnFm89jxyKiq8UPt/lxSsL/N1VOvNo5i2aB3QmW7I8/K0dxR+4Cx7i/KHz5JxrjJAfH2Q13ANhwPHHVKL1dhiiHncUfLUd31XmREHfCA+GtLc3lAK98xX6SzJS6ifkRxGlInVJJbhBfPwUZ70RJBxHKzVJr5A8=
    - secure: aD4re//j89fthO8x/AdKafB1oixJjhXgiC7KEHcCHtF8eCV2tvn4eRCSmYeMoysZGC5Ln9W8jjJk5FcJbbxLo+wPytsPTf5yD5OZ0cPoNuHb60fTCF/H4kzMEE91uvEdJ/IhOzhijBEoEhRYtYsJe9B9LDccAAHrEXWW111v2iRJopY1qgzrphQRP0f+wg3bafunxS7ZVGSq1WfySfbaDH/U3LgJjkmeMSSMDSJJ4/L1cgWRdSSLVz+1MyTMhGAhGWF94JupSQOZB3Y0IBFujJ6ZLNefO5lelItshabdD1KeBWBs4eruJNmZ4fFbSEH/0YwQE2E94OOkZuIMzXy5KX8kM0MexWALXhA0E1dqbPRCOxMXg4RbumiiBVJ0UhAM9feTDC36CYWzkNoLgnc8RdWPx2KXqVRabW3HocWjkoHRXp4nEPmMxL0RktDQtOLNf1MI/S/Nj7rR7kRk0+dvmKr4Nn7CyxCcUIYM8v0DYH3ZGhmbBnBFpgXr5lIhXpdEdarGOlsgXsV0BghRK7eeJf/stYV1QfdsHo/xbxA9R4ccz5pMk+AkbsLwLcH0W0ql29sydkWgmedQXA8a2rkmVBsWrSKJDC4chJqro3B7D8IvOmrIkd6UgXBEl5ZSgw+uxzeQoDC4v3KXaZJKM91bUco+8Iof1dKy6EH6nzLS3Zk=
    - secure: ohsHhBqbfVoIClmzHyzUGifuQIFln9cj6qppBX0dGMI0Y0U68Y9IBhRHBu/vjrXvRCy/sT4XwPOy6Wt1NQLLmdr8ic7c8qYx7D526qccbktMYgpOWTyPc0G3U6k+qOy7R9WXve4H5w0/vDsPR8xcwyXV9DCam5iMqhccCzJy3ygvcTA4UoX0tUfESHOEFzFjVzxAIyiVxWHU1LuziKr/lyflxTHCZFwjZBKSadKylBmeXQNlfNsTMaWiVkW6ZL7qXxwNhkvcHuItlVFEJ6x4iqMhi9XOdQ7R8fIylDHCZZZ3tr0QPta8lRSXl06w/B6ZHlt/8nBQ5WMG+4puPYwCKKcHIceKZGWfZGKtrUue9f8COFqIpetMB0uBwPrUbKQVceOO41CCgHaHWXBMXaRPz1Yy27tH9hSNMDstYs8guc+G+AZqJCzJhZoRbKwIlvoNwAWw/juV97K9iTLpeGLMnH8CZy2UwrLwIqW+mfBLWopC00PeM/UPtcmUa4CejupuXJd0sbPmhiu/XISiLlcp7olcE64R+7h+QHaNYGyG2XA/f0yjBO4dsV75fgUn0ptlH7r+HCwTQupzkZD5djmwhh9BR5iOdEGJ47m8LBMQYKtyjP67wmV0B8EYfnB+K+d7g060v24+4FA4QlU77vRyqg8qhxbTtLAY/ee0WR2b0to=
before_install:
  - openssl aes-256-cbc -K $encrypted_3e39b73e0d5c_key -iv $encrypted_3e39b73e0d5c_iv
    -in private.tar.enc -out private.tar -d
  - tar xvf private.tar
  - |
    if [ ! -d "$HOME/terraform/bin" ]; then
      rm -rf "$HOME/terraform"
      mkdir -p $HOME/terraform/bin
      wget https://releases.hashicorp.com/terraform/0.12.16/terraform_0.12.16_linux_amd64.zip
      unzip terraform_0.12.16_linux_amd64.zip -d $HOME/terraform/bin/
    fi
  - export PATH=$PATH:$HOME/terraform/bin
install:
  - yarn
jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn type-check
        - yarn build
    - stage: deploy
      env: CLOUD=AWS
      script:
        - yarn build
      before_deploy:
        - echo credentials \"app.terraform.io\" { token = \"$TOKEN\" } | cat >> ~/.terraformrc
        - cp -r ./node_modules ./dist/
        - terraform init
      deploy:
        - provider: script
          script: yarn deploy
          skip_cleanup: true
          on:
            branch: jwt
